export const FETCH_DATA_PRODUCTS = "FETCH_DATA_PRODUCTS";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILED = "FETCH_PRODUCTS_FAILED";

export const ADD_TO_CART = "ADD_TO_CART";
export const CLICK_MORE_ITEM = "CLICK_MORE_ITEM";
export const CLICK_LESS_ITEM = "CLICK_LESS_ITEM";
export const CLICK_REMOVE_ITEM = "CLICK_REMOVE_ITEM";
export const SET_VALUE_ITEM = "SET_VALUE_ITEM";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL";

